/* Registre des manuels. Les illustrations sont chargées à la demande. */
(()=>{'use strict';
const categories=[['monsters','Bestiaire et monstres'],['martial-arts','Arts martiaux'],['medicine','Médecine'],['alchemy','Alchimie'],['pills','Pilules'],['poisons','Poisons et antidotes'],['sects','Sectes actuelles'],['ancient-sects','Anciennes sectes'],['families','Familles et lignées'],['clans','Clans et organisations'],['qi','Qi et cultivation'],['meridians','Méridiens et circulation'],['weapons','Armes et forge'],['strategy','Stratégie et guerre'],['geography','Géographie et routes'],['cuisine','Cuisine et recettes'],['crafts','Artisanat'],['history','Histoire et chroniques']].map(([id,name])=>({id,name,portrait:`manual-category-${id}`}));
const types=['traité','journal','codex','guide','atlas','recueil','registre','fragment','rouleau','carnet','encyclopédie','manuel secret'];
const subjects=['des Cent Herbes','des Bêtes du Jianghu','des Neuf Méridiens','des Poings Anciens','des Pilules de Jade','des Familles Oubliées','des Sectes Disparues','des Routes du Nord','des Mille Saveurs','des Métaux Célestes','des Poisons Silencieux','des Principes du Qi','des Guerres Anciennes'];
const ranks=['Débutant','Basique','Commun','Adepte','Avancé','Expert','Maître','Grand Maître','Transcendant','Céleste','Saint','Divin'];
function createManual(i){const category=categories[i%categories.length],tier=Math.min(11,Math.floor(i/417));return {id:`MAN-${String(i+1).padStart(4,'0')}`,name:`${types[i%types.length]} ${subjects[Math.floor(i/categories.length)%subjects.length]}`,category:category.id,rank:ranks[tier],difficulty:10+tier*7+(i%19),type:types[i%types.length],readableAt:10+tier*7+(i%19),portrait:`manual-${String(i+1).padStart(4,'0')}`,damaged:i%13===0,pages:20+(i%181),secrets:i%13===0,knowledge:{language:10+(i%70),theory:10+tier*8+(i%23),qi:10+(i%90),body:10+(i%85),meridians:10+(i%90),spirit:10+(i%95)}}}
const manuals=Array.from({length:5000},(_,i)=>createManual(i));
if(typeof window!=='undefined'){window.MurimManualCategories=categories;window.MurimManuals=manuals;window.MurimContent=window.MurimContent||{};window.MurimContent.manualCategories=categories;window.MurimContent.manuals=manuals;window.MurimContent.createManual=createManual;}
if(typeof globalThis!=='undefined')globalThis.MurimManuals=manuals;
})();
