using Murim.World;

namespace Murim.Simulation;

public sealed class ActionSystem
{
    private readonly ObservationSystem _observations = new();
    public ActionResult Execute(WorldState world, CommandParseResult command)
    {
        ArgumentNullException.ThrowIfNull(world); ArgumentNullException.ThrowIfNull(command); var player = world.PlayerNpc;
        if (player is null) return Fail(command.Intent, "Aucun personnage joueur n'est initialisé."); if (!player.IsAlive) return Fail(command.Intent, "Ton personnage est mort. La partie continue, mais il ne peut plus agir."); if (!command.Success) return Fail(command.Intent, command.Feedback);
        try { return command.Intent switch { PlayerCommandIntent.Travel => Travel(world, player, command), PlayerCommandIntent.Observe => Observe(world, player), PlayerCommandIntent.Talk => Talk(world, player, command), PlayerCommandIntent.AskDirections => Social(world, player, command, "Demande son chemin", "Vous échangez des indications.", 8, 0.01), PlayerCommandIntent.Follow => Social(world, player, command, "Suit", "Tu suis cette personne pendant un moment.", 20, 0.005), PlayerCommandIntent.Help => Social(world, player, command, "Aide", "Tu apportes ton aide. La personne peut s'en souvenir.", 20, 0.03), PlayerCommandIntent.Refuse => Social(world, player, command, "Refus", "Tu refuses d'aider. Cette décision peut affecter la relation.", 5, -0.03), PlayerCommandIntent.Train => Train(world, player, command), PlayerCommandIntent.Eat => Consume(world, player, command, false), PlayerCommandIntent.Drink => Consume(world, player, command, true), PlayerCommandIntent.Sleep => Sleep(world, player), PlayerCommandIntent.InspectSelf => Inspect(world, player), PlayerCommandIntent.Examine => Examine(world, player), PlayerCommandIntent.Enter => Enter(world, player, command), PlayerCommandIntent.Exit => Exit(world, player), PlayerCommandIntent.Work => Work(world, player), PlayerCommandIntent.Buy => Market(world, player, command, false), PlayerCommandIntent.Sell => Market(world, player, command, true), PlayerCommandIntent.Investigate => Investigate(world, player), PlayerCommandIntent.DetectDanger => DetectDanger(world, player), _ => Fail(command.Intent, "Cette commande n'est pas encore disponible.") }; }
        catch (Exception ex) when (ex is InvalidOperationException or KeyNotFoundException) { return Fail(command.Intent, ex.Message); }
    }
    private static ActionResult Travel(WorldState world, Npc player, CommandParseResult command) { if (command.TargetLocationId is not Guid destination) return Fail(command.Intent, "Destination manquante."); var plan = world.Travel.Plan(world, player, destination, command.MovementMethod); if (plan is null || !world.Travel.Execute(world, plan)) return Fail(command.Intent, "Le voyage n'a pas pu être effectué."); return Ok(command.Intent, plan.DurationMinutes, $"Tu arrives à {world.Geography.Locations[destination].Name} après environ {plan.DurationMinutes} minutes."); }
    private ActionResult Observe(WorldState world, Npc player) { const int m = 10; var o = _observations.Observe(world, player); world.AdvanceMinutes(m); player.History.Add("Observation", player.AgeYears, $"Observe les alentours à {o.LocationName}."); return Ok(PlayerCommandIntent.Observe, m, ObservationFormatter.ToText(o)); }
    private static ActionResult Talk(WorldState world, Npc player, CommandParseResult command) => Social(world, player, command, "Conversation", "Tu échanges avec cette personne.", 15, 0.02);
    private static ActionResult Social(WorldState world, Npc player, CommandParseResult command, string title, string text, int minutes, double affinity) { if (command.TargetNpcId is not Guid id || !world.Npcs.TryGetValue(id, out var other) || !other.IsAlive) return Fail(command.Intent, "La personne n'est plus disponible."); if (player.CurrentLocationId != other.CurrentLocationId || player.CurrentBuildingId != other.CurrentBuildingId) return Fail(command.Intent, "Cette personne n'est pas dans le même espace que toi."); world.AdvanceMinutes(minutes); var relation = player.Relationships.FirstOrDefault(r => r.ToNpcId == other.Id); relation?.Shift(affinity, affinity > 0 ? 0.01 : -0.01, affinity > 0 ? 0.005 : 0); player.History.Add(title, player.AgeYears, $"{title} avec {other.Identity.DisplayName}."); other.History.Add(title, other.AgeYears, $"Interaction avec {player.Identity.DisplayName}."); return Ok(command.Intent, minutes, text); }
    private static ActionResult Train(WorldState world, Npc player, CommandParseResult command) { if (command.TargetTechniqueId is not Guid id) return Fail(command.Intent, "Technique manquante."); var r = world.Martial.Train(world, player, id, 30); return Ok(command.Intent, r.MinutesSpent, r.Outcome); }
    private static ActionResult Consume(WorldState world, Npc player, CommandParseResult command, bool drink) { if (command.TargetItemId is not Guid id || !world.Inventory.Items.TryGetValue(id, out var item)) return Fail(command.Intent, "Objet introuvable."); var entry = player.Inventory.Entries.FirstOrDefault(e => e.ItemId == id && e.Quantity > 0); if (entry is null || !item.Consumable) return Fail(command.Intent, "Cet objet ne peut pas être consommé."); if (!drink && item.Category != ItemCategory.Food) return Fail(command.Intent, "Ce n'est pas un aliment."); player.Inventory.Remove(id); const int m = 5; world.AdvanceMinutes(m); if (drink) player.Needs.Drink(35); else player.Needs.Eat(35); return Ok(command.Intent, m, drink ? $"Tu bois {item.Name}." : $"Tu manges {item.Name}."); }
    private static ActionResult Sleep(WorldState world, Npc player) { const int m = 480; world.AdvanceMinutes(m); player.Needs.SleepFor(100); player.History.Add("Sommeil", player.AgeYears, "Dort plusieurs heures."); return Ok(PlayerCommandIntent.Sleep, m, "Tu dors. Le monde continue pendant ton sommeil."); }
    private static ActionResult Inspect(WorldState world, Npc player) { const int m = 5; world.AdvanceMinutes(m); var loc = player.CurrentLocationId is Guid id && world.Geography.Locations.TryGetValue(id, out var l) ? l.Name : "inconnu"; var building = player.CurrentBuildingId is Guid bid && world.Buildings.TryGet(bid, out var b) ? b.Name : "extérieur"; return Ok(PlayerCommandIntent.InspectSelf, m, $"Profil : {player.Identity.DisplayName}, âge {player.AgeYears} ans, lieu {loc}, espace {building}, faim {player.Needs.Hunger:0.#}, soif {player.Needs.Thirst:0.#}, fatigue {player.Needs.Fatigue:0.#}, douleur {player.CurrentPain:0.#}."); }
    private static ActionResult Examine(WorldState world, Npc player) { const int m = 8; if (player.CurrentLocationId is not Guid id || !world.Geography.Locations.TryGetValue(id, out var l)) return Fail(PlayerCommandIntent.Examine, "Le lieu est inconnu."); var buildingText = player.CurrentBuildingId is Guid bid && world.Buildings.TryGet(bid, out var b) ? $" Intérieur : {b.Name}. {b.Description} Occupants : {world.Buildings.Occupants(world, b).Count()}." : $" Bâtiments visibles : {world.Buildings.AtLocation(id).Count()} ."; world.AdvanceMinutes(m); return Ok(PlayerCommandIntent.Examine, m, $"Tu examines {l.Name}. Type : {l.Type}. Région : {l.Region}. Population : {l.Population}. Danger connu : {l.DangerLevel}/100.{buildingText}"); }
    private static ActionResult Enter(WorldState world, Npc player, CommandParseResult command) { const int m = 5; if (player.CurrentBuildingId is not null) return Fail(command.Intent, "Tu es déjà à l'intérieur d'un bâtiment."); if (player.CurrentLocationId is not Guid locationId) return Fail(command.Intent, "Aucun lieu identifiable."); Building? building = command.TargetBuildingId is Guid bid && world.Buildings.TryGet(bid, out var target) ? target : world.Buildings.AtLocation(locationId).FirstOrDefault(b => b.IsOpen(world.Time.Period)); if (building is null) return Fail(command.Intent, "Aucun bâtiment accessible ici à cette période."); if (!world.Buildings.CanEnter(world, player, building, out var reason)) return Fail(command.Intent, reason); player.EnterBuilding(building.Id); player.DiscoverLocation(locationId); world.AdvanceMinutes(m); player.History.Add("Entrée", player.AgeYears, $"Entre dans {building.Name}."); return Ok(command.Intent, m, $"Tu entres dans {building.Name}. {building.Description} Occupants visibles : {world.Buildings.Occupants(world, building).Count()}."); }
    private static ActionResult Exit(WorldState world, Npc player) { const int m = 3; if (player.CurrentBuildingId is not Guid id || !world.Buildings.TryGet(id, out var building)) return Fail(PlayerCommandIntent.Exit, "Tu es déjà à l'extérieur."); player.ExitBuilding(); world.AdvanceMinutes(m); player.History.Add("Sortie", player.AgeYears, $"Sort de {building.Name}."); return Ok(PlayerCommandIntent.Exit, m, $"Tu sors de {building.Name}."); }
    private static ActionResult Work(WorldState world, Npc player) { const int m = 60; var building = player.CurrentBuildingId is Guid bid && world.Buildings.TryGet(bid, out var b) ? b : null; if (building is not null && building.Type is not (BuildingType.Workshop or BuildingType.Shop or BuildingType.Inn or BuildingType.Farmhouse)) return Fail(PlayerCommandIntent.Work, "Ce bâtiment n'est pas un lieu de travail approprié."); world.AdvanceMinutes(m); var income = Math.Max(0, player.Profession.DailyIncome / 8.0); player.ApplyWealthChange(income); if (building is not null) building.WorkerNpcIds.Add(player.Id); player.History.Add("Travail", player.AgeYears, $"Travaille pendant une heure et gagne environ {income:0.##} unités monétaires."); return Ok(PlayerCommandIntent.Work, m, $"Tu travailles pendant une heure. Gain : {income:0.##}. Wealth : {player.Wealth:0.##}."); }
    private static ActionResult Market(WorldState world, Npc player, CommandParseResult command, bool sell) { const int m = 15; var intent = sell ? PlayerCommandIntent.Sell : PlayerCommandIntent.Buy; var business = world.Commerce.FindOpenBusiness(world, player); if (business is null) return Fail(intent, sell ? "Aucun commerce acheteur n'est ouvert ici." : "Aucun commerce ouvert ici."); if (sell) { world.AdvanceMinutes(m); return Ok(intent, m, world.Commerce.Describe(world, business) + " Pour vendre, un acheteur doit être disponible dans un commerce ou sur le marché."); } var stock = command.TargetItemId is Guid itemId ? business.Stock.FirstOrDefault(s => s.ItemId == itemId) : business.Stock.FirstOrDefault(s => s.Quantity > 0); if (stock is null || stock.Quantity <= 0) return Fail(intent, "Le commerce n'a pas cet article en stock."); if (!world.Commerce.Buy(world, player, business, stock.ItemId, 1, out var total)) return Fail(intent, $"Achat impossible : fonds insuffisants, stock indisponible ou vendeur absent. Prix demandé : {total:0.##}."); world.AdvanceMinutes(m); var item = world.Inventory.Items[stock.ItemId]; return Ok(intent, m, $"Tu achètes {item.Name} pour {total:0.##}. Il reste {player.Wealth:0.##} unités monétaires."); }
    private static ActionResult Investigate(WorldState world, Npc player) { const int m = 20; if (player.CurrentLocationId is not Guid id || !world.Geography.Locations.TryGetValue(id, out var l)) return Fail(PlayerCommandIntent.Investigate, "Tu n'as pas de lieu exploitable à enquêter."); world.AdvanceMinutes(m); player.History.Add("Enquête", player.AgeYears, $"Enquête autour de {l.Name}."); return Ok(PlayerCommandIntent.Investigate, m, $"Tu enquêtes autour de {l.Name}. Les informations réellement découvrables dépendront des témoins, traces et connaissances disponibles."); }
    private static ActionResult DetectDanger(WorldState world, Npc player) { const int m = 10; if (player.CurrentLocationId is not Guid id || !world.Geography.Locations.TryGetValue(id, out var l)) return Fail(PlayerCommandIntent.DetectDanger, "Impossible d'évaluer le danger ici."); world.AdvanceMinutes(m); var e = world.Environment.Get(id); var road = world.Geography.RoadsFrom(id).MaxBy(r => r.DangerLevel); var danger = Math.Max(l.DangerLevel, road?.DangerLevel ?? 0); return Ok(PlayerCommandIntent.DetectDanger, m, $"Évaluation : danger connu {danger}/100. Météo {e.Weather}, visibilité {e.VisibilityKm:0.#} km, vent {e.WindKph:0.#} km/h."); }
    private static ActionResult Ok(PlayerCommandIntent i, int m, string f) => new() { Success = true, Intent = i, MinutesSpent = m, Feedback = f }; private static ActionResult Fail(PlayerCommandIntent i, string f) => new() { Success = false, Intent = i, MinutesSpent = 0, Feedback = f };
}
