/* Murim — système Corps / Constitution / Méridiens / Esprit
 * Règle canonique : 95 % des êtres naissent avec un corps ordinaire.
 * Une constitution spéciale est innée à la naissance, ou peut exceptionnellement
 * être acquise grâce à un manuel de niveau divin. Les manuels divins sont
 * extrêmement rares et ne garantissent jamais la réussite.
 */
(function(){'use strict';
const W=window;if(W.MurimBody)return;
const ordinary=['Corps ordinaire','Neutre','Le corps humain commun du Jianghu.'];
const special=[['Corps robuste','Physique','Physique naturellement supérieur.'],['Os de fer','Physique','Bonne résistance aux impacts et à l’entraînement corporel.'],['Corps de Jade','Qi','Circulation du Qi naturellement stable.'],['Corps du Tigre','Physique','Excellent potentiel pour les arts de force et le combat rapproché.'],['Corps du Dragon dormant','Rare','Potentiel immense mais extrêmement difficile à éveiller.'],['Corps céleste','Rare','Affinités inhabituelles avec certaines techniques avancées.'],['Corps du Phénix','Rare','Récupération et adaptation exceptionnelles, avec risques de surcharge.'],['Corps du Néant','Anormal','Affinités imprévisibles et dangereuses.']];
const meridians=[['Méridiens normaux','Stable','Circulation régulière.'],['Méridiens ouverts','Fluide','Le Qi circule facilement mais les excès sont dangereux.'],['Méridiens denses','Puissant','Grande capacité de stockage, progression plus lente.'],['Méridiens de foudre','Foudre','Qi rapide et violent ; risque de lésions internes.'],['Méridiens de glace','Glace','Qi froid ; certaines techniques deviennent plus compatibles.'],['Méridiens de feu','Feu','Qi chaud ; risque de brûlure interne en cas de mauvaise maîtrise.'],['Méridiens empoisonnés','Poison','Résistance et affinité aux poisons ; contamination possible des alliés.'],['Méridiens fragmentés','Instable','Circulation irrégulière ; certaines techniques deviennent dangereuses.'],['Méridiens inversés','Anormal','Flux du Qi atypique ; incompatibilités fréquentes.']];
const spirits=[['Esprit ordinaire','Stable'],['Esprit clair','Bonne compréhension'],['Esprit aiguisé','Apprentissage accéléré'],['Esprit de Jade','Résistance mentale'],['Esprit céleste','Rare potentiel'],['Esprit du Néant','Anormal et imprévisible']];
const pick=a=>a[Math.floor(Math.random()*a.length)];
function rollConstitution(){return Math.random()<0.95?ordinary:pick(special);}
function build(){if(!W.S||!W.S.player)return;const p=W.S.player;if(!p.bodyProfile){const b=rollConstitution(),m=pick(meridians),s=pick(spirits);p.bodyProfile={constitution:b[0],category:b[1],description:b[2],meridian:m[0],meridianType:m[1],meridianDescription:m[2],spirit:s[0],spiritType:s[1],discovered:false,mutation:null,source:'naissance',healthBaseline:p.health||100};}render();}
function card(a,b,c){return '<div class="body-card"><span>'+a+'</span><b>'+b+'</b><small>'+c+'</small></div>';}
function render(){const p=W.S&&W.S.player;if(!p)return;let box=document.getElementById('bodyProfile');if(!box){const portrait=document.getElementById('portraitBox');if(!portrait)return;box=document.createElement('div');box.id='bodyProfile';box.className='section body-profile';portrait.parentNode.insertBefore(box,portrait.nextSibling);}const b=p.bodyProfile||{};box.innerHTML='<h2>Corps & Esprit</h2><div class="body-grid">'+card('Constitution',b.discovered?b.constitution:'Inconnue',b.discovered?b.description:'Ton corps n\'a pas encore été correctement examiné.')+card('Méridiens',b.discovered?b.meridian:'Inconnus',b.discovered?b.meridianDescription:'Une observation approfondie ou un médecin peut révéler leur état.')+card('Esprit',b.discovered?b.spirit:'Inconnu',b.discovered?'État : '+b.spiritType:'Non évalué.')+'</div><div class="body-meta">'+(b.discovered?'Constitution examinée':'Découverte progressive')+(b.source?' · Origine : '+b.source:'')+(b.mutation?' · Mutation : '+b.mutation:'')+'</div>';}
function discover(){if(W.S&&W.S.player){build();W.S.player.bodyProfile.discovered=true;render();if(typeof W.render==='function')W.render();}}
function attemptDivineManual(manual){if(!W.S||!W.S.player||!manual)return {success:false,reason:'Aucun manuel.'};if(manual.level!=='divin')return {success:false,reason:'Seul un manuel de niveau divin peut tenter une acquisition de constitution.'};const success=Math.random()<Number(manual.successChance||0.01);if(!success)return {success:false,reason:'Le corps ne supporte pas la transformation.'};const b=pick(special),p=W.S.player;p.bodyProfile=p.bodyProfile||{};p.bodyProfile.constitution=b[0];p.bodyProfile.category=b[1];p.bodyProfile.description=b[2];p.bodyProfile.source='manuel divin';p.bodyProfile.discovered=true;p.bodyProfile.mutation='acquise par un manuel divin';render();if(typeof W.render==='function')W.render();return {success:true,constitution:b[0]};}
W.MurimBody={build,render,discover,attemptDivineManual,rollConstitution};
const boot=setInterval(()=>{if(W.S&&W.S.player){build();clearInterval(boot)}},200);const oldNew=W.newLife;if(typeof oldNew==='function')W.newLife=function(){const r=oldNew.apply(this,arguments);setTimeout(build,30);return r;};
})();
