/* Murim — interface RPG/gestion V5.2 */
(function(){'use strict';if(window.__murimRPGUIv5)return;window.__murimRPGUIv5=true;const D=document;
const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function make(t,c,h){const e=D.createElement(t);if(c)e.className=c;if(h!==undefined)e.innerHTML=h;return e}function S(){return window.S||{}}
function inject(){const wrap=D.querySelector('.wrap'),layout=D.querySelector('.layout'),top=D.querySelector('.top');if(!wrap||!layout||!top)return false;
 if(!D.getElementById('murimRpgHud')){const h=make('section','murim-rpg-hud');h.id='murimRpgHud';h.innerHTML='<div class="rpg-hud-main"><div class="rpg-campaign"><span class="rpg-kicker">CHRONIQUE</span><strong>Les Mille Destins</strong><span id="rpgDate">—</span></div><div class="rpg-hud-stats"><div><small>ÂGE</small><b id="rpgAge">—</b></div><div><small>LIEU</small><b id="rpgLoc">—</b></div><div><small>QI</small><b id="rpgQi">—</b></div><div><small>RÉPUTATION</small><b id="rpgRep">—</b></div></div></div><div class="rpg-world-state"><span class="rpg-live-dot"></span><span id="rpgWorld">Jianghu en attente</span><button type="button" id="rpgFocusBtn">Immersion</button></div>';top.insertAdjacentElement('afterend',h)}
 if(!D.getElementById('murimRpgNav')){const n=make('nav','murim-rpg-nav');n.id='murimRpgNav';n.innerHTML='<button data-target="chronique" class="active">⚔ Chronique</button><button data-target="carte">🗺 Carte</button><button data-target="personnages">👥 Jianghu</button><button data-target="economie">◈ Économie</button><button data-target="organisations">☯ Factions</button><span class="rpg-nav-spacer"></span><button data-action="compact">▣ Densité</button>';layout.parentNode.insertBefore(n,layout);n.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='compact'){D.body.classList.toggle('murim-compact');return}const target=b.dataset.target;n.querySelectorAll('[data-target]').forEach(x=>x.classList.toggle('active',x===b));focus(target)})}
 decorate();return true}
function focus(t){const map=D.getElementById('map'),people=D.getElementById('people'),eco=D.getElementById('economy'),org=D.getElementById('orgs'),story=D.getElementById('story');const el={chronique:story,carte:map,personnages:people,economie:eco,organisations:org}[t];if(el)el.scrollIntoView({behavior:'smooth',block:'nearest'})}
function decorate(){const L=D.querySelector('.layout>aside:first-child'),M=D.querySelector('.layout>main'),R=D.querySelector('.layout>aside:last-child');if(L&&!L.querySelector('.rpg-panel-label'))L.insertAdjacentHTML('afterbegin','<div class="rpg-panel-label">FICHE DU DESTIN</div>');if(M&&!M.querySelector('.rpg-panel-label'))M.insertAdjacentHTML('afterbegin','<div class="rpg-panel-label">FIL DE DESTINÉE</div>');if(R&&!R.querySelector('.rpg-panel-label'))R.insertAdjacentHTML('afterbegin','<div class="rpg-panel-label">ÉTAT DU JIANGHU</div>');const p=D.getElementById('portraitBox');if(p)p.classList.add('rpg-portrait-stage');const story=D.getElementById('story');if(story)story.classList.add('rpg-story-window')}
function update(){const s=S(),p=s.player||{},set=(id,v)=>{const e=D.getElementById(id);if(e)e.textContent=v??'—'};set('rpgDate',typeof window.now==='function'?window.now():'—');set('rpgAge',p.age==null?'—':p.age+' an'+(p.age>1?'s':''));set('rpgLoc',p.location||p.region||'—');set('rpgQi',p.qi==null?'—':p.qi);set('rpgRep',p.reputation==null?'—':p.reputation);set('rpgWorld',`${(s.npcs||[]).filter(n=>n.alive).length} PNJ vivants · ${(s.rumors||[]).length} rumeurs`);const b=D.querySelector('.brand');if(b)b.textContent='武林 · MURIM'}
function boot(){if(!inject()){setTimeout(boot,120);return}update();const b=D.getElementById('rpgFocusBtn');if(b)b.onclick=()=>D.body.classList.toggle('murim-focus');D.addEventListener('click',()=>setTimeout(update,80),true);D.addEventListener('change',()=>setTimeout(update,80),true);setInterval(update,1000)}if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();
