namespace Murim.World;

public enum LoanStatus { Active, Repaid, Defaulted }
public sealed class BankAccount { public Guid Id{get;}=Guid.NewGuid(); public Guid OwnerNpcId{get;init;} public double Balance{get;set;} public long OpenedDay{get;init;} public bool Active{get;set;}=true; }
public sealed class Loan { public Guid Id{get;}=Guid.NewGuid(); public Guid BorrowerNpcId{get;init;} public Guid LenderNpcId{get;init;} public double Principal{get;init;} public double Remaining{get;set;} public double MonthlyRate{get;init;} public int TermDays{get;init;} public long StartDay{get;init;} public LoanStatus Status{get;set;}=LoanStatus.Active; public string Purpose{get;init;}="Crédit"; }
public sealed class BankingRecord { public long Day{get;init;} public Guid LoanId{get;init;} public string Event{get;init;}=string.Empty; public double Amount{get;init;} }
public sealed class BankingSystem
{
 private readonly Dictionary<Guid,BankAccount> _accounts=new(); private readonly Dictionary<Guid,Loan> _loans=new(); public IReadOnlyDictionary<Guid,BankAccount> Accounts=>_accounts; public IReadOnlyDictionary<Guid,Loan> Loans=>_loans; public List<BankingRecord> History{get;}=new();
 public BankAccount OpenAccount(WorldState world,Npc owner,double initial=0){var a=new BankAccount{OwnerNpcId=owner.Id,Balance=Math.Max(0,initial),OpenedDay=world.Time.Day};_accounts[a.Id]=a;return a;}
 public Loan? Borrow(WorldState world,Npc borrower,Npc lender,double amount,double monthlyRate=.015,int termDays=180,string purpose="Crédit"){if(!borrower.IsAlive||!lender.IsAlive||borrower.Id==lender.Id||amount<=0||lender.Wealth<amount)return null;var debt=_loans.Values.Where(x=>x.BorrowerNpcId==borrower.Id&&x.Status==LoanStatus.Active).Sum(x=>x.Remaining);if(debt>Math.Max(5,borrower.Wealth*3))return null;lender.ApplyWealthChange(-amount);borrower.ApplyWealthChange(amount);var loan=new Loan{BorrowerNpcId=borrower.Id,LenderNpcId=lender.Id,Principal=amount,Remaining=amount,MonthlyRate=Math.Clamp(monthlyRate,.001,.1),TermDays=Math.Max(30,termDays),StartDay=world.Time.Day,Purpose=purpose};_loans[loan.Id]=loan;History.Add(new BankingRecord{Day=world.Time.Day,LoanId=loan.Id,Event="Prêt accordé",Amount=amount});return loan;}
 public bool Repay(WorldState world,Npc borrower,Loan loan,double amount,out string feedback){feedback=string.Empty;if(loan.Status!=LoanStatus.Active||loan.BorrowerNpcId!=borrower.Id||amount<=0){feedback="Crédit invalide.";return false;}var payment=Math.Min(amount,loan.Remaining);if(borrower.Wealth<payment){feedback="Liquidités insuffisantes.";return false;}borrower.ApplyWealthChange(-payment);if(world.Npcs.TryGetValue(loan.LenderNpcId,out var lender)&&lender.IsAlive)lender.ApplyWealthChange(payment);loan.Remaining-=payment;if(loan.Remaining<=.01){loan.Remaining=0;loan.Status=LoanStatus.Repaid;}History.Add(new BankingRecord{Day=world.Time.Day,LoanId=loan.Id,Event=loan.Status==LoanStatus.Repaid?"Crédit remboursé":"Remboursement",Amount=payment});feedback=$"Remboursement de {payment:0.##}.";return true;}
 public void AdvanceDay(WorldState world){foreach(var loan in _loans.Values.Where(x=>x.Status==LoanStatus.Active).ToList()){if(!world.Npcs.TryGetValue(loan.BorrowerNpcId,out var borrower)||!borrower.IsAlive){loan.Status=LoanStatus.Defaulted;continue;}if((world.Time.Day-loan.StartDay)%30!=0||world.Time.Day==loan.StartDay)continue;var interest=loan.Remaining*loan.MonthlyRate;loan.Remaining+=interest;var scheduled=Math.Min(loan.Remaining,loan.Principal/Math.Max(1,loan.TermDays/30.0));if(borrower.Wealth>=scheduled){borrower.ApplyWealthChange(-scheduled);if(world.Npcs.TryGetValue(loan.LenderNpcId,out var lender)&&lender.IsAlive)lender.ApplyWealthChange(scheduled);loan.Remaining-=scheduled;History.Add(new BankingRecord{Day=world.Time.Day,LoanId=loan.Id,Event="Échéance payée",Amount=scheduled});}else if(world.Time.Day-loan.StartDay>loan.TermDays){loan.Status=LoanStatus.Defaulted;History.Add(new BankingRecord{Day=world.Time.Day,LoanId=loan.Id,Event="Défaut de paiement",Amount=loan.Remaining});}}}
 public string DescribeDebt(Npc npc)=>_loans.Values.Where(x=>x.BorrowerNpcId==npc.Id&&x.Status==LoanStatus.Active).Select(x=>$"{x.Purpose}: {x.Remaining:0.##} restant").DefaultIfEmpty("Aucune dette active.").Aggregate((a,b)=>a+" ; "+b);
}