#define UNICODE
#define _UNICODE
#include <windows.h>
#include <gdiplus.h>
#include <commdlg.h>
#include <string>
#include <sstream>
#include <fstream>
#include <random>
#include <vector>
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include "murim_engine.hpp"

#pragma comment(lib, "gdiplus.lib")
using namespace Gdiplus;

namespace {
constexpr int ID_NEW=1001, ID_ADVANCE=1002, ID_SAVE=1003, ID_LOAD=1004, ID_FULL=1005;
constexpr int ID_ACTION_EDIT=1010, ID_ACTION=1011, ID_TRAIN=1012, ID_REST=1013;

struct GameState {
    bool started=false; int ageMonths=0;
    std::wstring name=L"Inconnu", place=L"Village de naissance";
    std::wstring body=L"Corps ordinaire", spirit=L"Esprit ordinaire", qi=L"Qi naturel";
    std::wstring trait=L"Observateur", title=L"Aucun titre";
    int money=20, health=100, stamina=100, comprehension=10;
    int trainingHours=0, martialSkill=1;
    bool constitutionRevealed=false;
    std::uint64_t seed=0; murim::WorldEngine world{318};
} state;

HWND hAction{}, hLog{}; HFONT hFont{}, hSmall{}; ULONG_PTR gdiplusToken{}; Image* portrait=nullptr;

std::wstring ageText(){ if(!state.started)return L"—"; if(state.ageMonths<12)return std::to_wstring(state.ageMonths)+L" mois"; int y=state.ageMonths/12,m=state.ageMonths%12; return std::to_wstring(y)+(y>1?L" ans":L" an")+(m?L" et "+std::to_wstring(m)+L" mois":L""); }
void logLine(const std::wstring&s){if(!hLog)return;int n=GetWindowTextLengthW(hLog);SendMessageW(hLog,EM_SETSEL,n,n);std::wstring x=s+L"\r\n";SendMessageW(hLog,EM_REPLACESEL,FALSE,(LPARAM)x.c_str());}
void addButton(HWND p,const wchar_t*t,int id){HWND b=CreateWindowW(L"BUTTON",t,WS_CHILD|WS_VISIBLE|BS_OWNERDRAW,0,0,100,34,p,(HMENU)(INT_PTR)id,GetModuleHandleW(nullptr),nullptr);SendMessageW(b,WM_SETFONT,(WPARAM)hFont,TRUE);}
void panel(Graphics&g,RectF r){SolidBrush b(Color(255,15,22,31));Pen p(Color(255,48,61,76),1.2f);g.FillRectangle(&b,r);g.DrawRectangle(&p,r.X,r.Y,r.Width,r.Height);}
void text(Graphics&g,const std::wstring&s,float x,float y,float size,Color c,bool bold=false){FontFamily ff(L"Georgia");Font f(&ff,size,bold?FontStyleBold:FontStyleRegular,UnitPixel);SolidBrush b(c);g.DrawString(s.c_str(),-1,&f,PointF(x,y),&b);}
void drawPortrait(Graphics&g,RectF r){SolidBrush b(Color(255,26,32,40));g.FillRectangle(&b,r);Pen p(Color(255,190,150,76),2);g.DrawRectangle(&p,r.X,r.Y,r.Width,r.Height);if(portrait&&portrait->GetLastStatus()==Ok){float iw=(float)portrait->GetWidth(),ih=(float)portrait->GetHeight(),sc=std::min(r.Width/iw,r.Height/ih);float w=iw*sc,h=ih*sc;g.DrawImage(portrait,r.X+(r.Width-w)/2,r.Y+(r.Height-h)/2,w,h);}else{text(g,L"PORTRAIT IA",r.X+44,r.Y+78,18,Color(255,190,150,76),true);text(g,state.started?state.name:L"Jianghu",r.X+24,r.Y+112,16,Color(255,235,225,210));}}

void paintUI(HWND hwnd){RECT rr;GetClientRect(hwnd,&rr);int W=rr.right,H=rr.bottom;HDC dc=GetDC(hwnd);Graphics g(dc);g.SetSmoothingMode(SmoothingModeAntiAlias);SolidBrush bg(Color(255,7,10,15));g.FillRectangle(&bg,0,0,W,H);SolidBrush top(Color(255,13,19,28));g.FillRectangle(&top,0,0,W,72);
text(g,L"武林 · MURIM",28,12,28,Color(255,224,185,111),true);text(g,L"LES MILLE DESTINS",31,43,11,Color(255,150,158,168));text(g,L"JIANGHU VIVANT · SIMULATION",330,27,13,Color(255,175,184,194));text(g,L"ANNÉE 318",W-170,17,12,Color(255,205,173,112));text(g,state.started?ageText():L"—",W-170,39,12,Color(255,155,165,174));
float gap=14,left=22,top=88,pw=250,rw=285,cw=W-left-pw-rw-gap*2;if(cw<420)cw=420;RectF lp(left,top,pw,H-top-22),cp(left+pw+gap,top,cw,H-top-22),rp(left+pw+gap+cw+gap,top,rw,H-top-22);panel(g,lp);panel(g,cp);panel(g,rp);
text(g,L"TA VIE",lp.X+18,lp.Y+15,20,Color(255,224,185,111),true);drawPortrait(g,RectF(lp.X+18,lp.Y+52,lp.Width-36,190));
if(state.started){text(g,state.name,lp.X+18,lp.Y+253,18,Color(255,240,234,220),true);text(g,state.title,lp.X+18,lp.Y+278,12,Color(255,198,161,91));text(g,L"Âge · "+ageText(),lp.X+18,lp.Y+302,12,Color(255,160,169,178));text(g,L"Lieu · "+state.place,lp.X+18,lp.Y+323,12,Color(255,160,169,178));text(g,L"CORPS",lp.X+18,lp.Y+357,12,Color(255,224,185,111),true);text(g,state.constitutionRevealed?state.body:L"??? · à découvrir",lp.X+18,lp.Y+378,14,Color(255,232,225,210));text(g,L"ESPRIT",lp.X+18,lp.Y+410,12,Color(255,224,185,111),true);text(g,state.spirit,lp.X+18,lp.Y+431,14,Color(255,232,225,210));text(g,L"QI",lp.X+18,lp.Y+463,12,Color(255,224,185,111),true);text(g,state.qi,lp.X+18,lp.Y+484,14,Color(255,232,225,210));text(g,L"Santé · "+std::to_wstring(state.health)+L" / 100",lp.X+18,lp.Y+516,12,Color(255,150,210,165));text(g,L"Endurance · "+std::to_wstring(state.stamina)+L" / 100",lp.X+18,lp.Y+538,12,Color(255,150,190,220));}else text(g,L"Aucune vie en cours",lp.X+18,lp.Y+270,14,Color(255,155,165,174));
text(g,L"CHRONIQUE",cp.X+18,cp.Y+15,20,Color(255,224,185,111),true);text(g,state.started?L"Tu n'es pas le héros. Le Jianghu continue sans toi.":L"Crée une vie pour entrer dans le Jianghu.",cp.X+18,cp.Y+48,12,Color(255,184,191,198));RectF scene(cp.X+18,cp.Y+76,cp.Width-36,148);panel(g,scene);text(g,state.started?state.place:L"Lieu actuel",scene.X+16,scene.Y+17,19,Color(255,239,226,202),true);text(g,L"Illustration IA du lieu · chargement à la demande",scene.X+16,scene.Y+50,12,Color(255,150,160,171));text(g,L"Routes · météo · habitants · bâtiments · événements",scene.X+16,scene.Y+75,11,Color(255,150,160,171));
text(g,L"ACTION LIBRE",cp.X+18,cp.Y+250,15,Color(255,224,185,111),true);text(g,L"Aucune quête obligatoire : tu choisis ta vie.",cp.X+18,cp.Y+273,11,Color(255,145,155,166));text(g,L"PROGRESSION",cp.X+18,cp.Y+385,15,Color(255,224,185,111),true);text(g,L"Entraînement · "+std::to_wstring(state.trainingHours)+L" h ce mois",cp.X+18,cp.Y+412,13,Color(255,226,219,202));text(g,L"Maîtrise martiale · "+std::to_wstring(state.martialSkill),cp.X+18,cp.Y+435,13,Color(255,226,219,202));text(g,L"Qualité > quantité · fatigue · blessures · récupération",cp.X+18,cp.Y+458,11,Color(255,145,155,166));
text(g,L"JIANGHU",rp.X+18,rp.Y+15,20,Color(255,224,185,111),true);const wchar_t* lines[]={L"PERSONNES · PNJ, famille, maîtres",L"RELATIONS · confiance, dette, rivalité",L"DÉCOUVERTE · observer, lire, étudier",L"MANUELS · arts, médecine, cuisine, monstres",L"TECHNIQUES · débutant → divin",L"CORPS · constitutions, méridiens, mutations",L"QI · affinités, mutations, dangers",L"FACTIONS · sectes, familles, clans, cultes",L"ÉCONOMIE · métiers, commerce, ressources",L"TITRES · réputation et accomplissements"};for(int i=0;i<10;i++){text(g,lines[i],rp.X+18,rp.Y+58+i*38,11,Color(255,160,169,178),i==0);}text(g,L"Découvrir demande des actions : si tu ne vois pas, tu ne sais pas.",rp.X+18,rp.Y+rp.Height-46,11,Color(255,150,210,165));ReleaseDC(hwnd,dc);}

void layout(HWND hwnd){RECT r;GetClientRect(hwnd,&r);int W=r.right,H=r.bottom;MoveWindow(hAction,430,350,std::max(390,W-735),62,TRUE);HWND b; if((b=GetDlgItem(hwnd,ID_ACTION)))MoveWindow(b,430,416,130,36,TRUE);if((b=GetDlgItem(hwnd,ID_TRAIN)))MoveWindow(b,570,416,130,36,TRUE);if((b=GetDlgItem(hwnd,ID_REST)))MoveWindow(b,710,416,130,36,TRUE);if((b=GetDlgItem(hwnd,ID_NEW)))MoveWindow(b,W-225,18,100,36,TRUE);if((b=GetDlgItem(hwnd,ID_SAVE)))MoveWindow(b,W-120,18,100,36,TRUE);if((b=GetDlgItem(hwnd,ID_LOAD)))MoveWindow(b,W-225,58,100,32,TRUE);if((b=GetDlgItem(hwnd,ID_FULL)))MoveWindow(b,W-120,58,100,32,TRUE);MoveWindow(hLog,430,510,std::max(390,W-735),std::max(100,H-535),TRUE);}
void redraw(HWND h){InvalidateRect(h,nullptr,FALSE);}
void newLife(HWND hwnd){std::random_device rd;state=GameState{};state.started=true;state.seed=(static_cast<std::uint64_t>(rd())<<32)^rd();state.world=murim::WorldEngine(state.seed);state.name=(rd()%2)?L"Wei Jun":L"Jin Han";state.place=L"Village de Qingshui";state.world.add_person({1,30,"Village de Qingshui",true});state.world.add_person({2,28,"Village de Qingshui",true});state.world.add_person({3,6,"Village de Qingshui",true});SetWindowTextW(hAction,L"");logLine(L"Une nouvelle vie commence.");logLine(L"Tu es un habitant du Jianghu, pas un héros prédestiné.");logLine(L"Ton corps et les secrets rares ne sont pas révélés gratuitement.");logLine(L"Tu choisis tes entraînements, ton travail, tes relations et tes voyages.");redraw(hwnd);}
void advanceTime(HWND hwnd){if(!state.started)return;state.ageMonths++;state.stamina=std::min(100,state.stamina+15);state.world.advance_days(30);logLine(state.ageMonths==12?L"Une année s'est écoulée.":L"Un nouveau mois s'écoule dans le Jianghu.");redraw(hwnd);}
void doAction(HWND hwnd){if(!state.started)return;wchar_t buf[1024]{};GetWindowTextW(hAction,buf,1024);std::wstring a=buf;if(a.empty()){logLine(L"Aucune action indiquée.");return;}int days=(a.find(L"voyage")!=std::wstring::npos||a.find(L"retour")!=std::wstring::npos)?7:1;state.world.advance_days(days);state.stamina=std::max(0,state.stamina-days*2);logLine(L"Action : "+a+L" · "+std::to_wstring(days)+L" jour(s).");SetWindowTextW(hAction,L"");redraw(hwnd);}
void train(HWND hwnd){if(!state.started)return;if(state.ageMonths<36){logLine(L"Tu es trop jeune pour un entraînement martial structuré.");return;}state.trainingHours+=2;state.stamina=std::max(0,state.stamina-10);if(state.stamina<20){state.health=std::max(1,state.health-2);logLine(L"Surentraînement : fatigue et risque de blessure.");}else{state.martialSkill++;logLine(L"Deux heures d'entraînement : ta maîtrise progresse.");}state.world.advance_days(1);redraw(hwnd);}
void rest(HWND hwnd){if(!state.started)return;state.stamina=std::min(100,state.stamina+30);state.health=std::min(100,state.health+3);state.world.advance_days(1);logLine(L"Repos : récupération physique.");redraw(hwnd);}
void saveGame(HWND hwnd){OPENFILENAMEW o{};wchar_t p[MAX_PATH]=L"murim-save.sav";o.lStructSize=sizeof(o);o.hwndOwner=hwnd;o.lpstrFile=p;o.nMaxFile=MAX_PATH;o.lpstrFilter=L"Murim Save (*.sav)\0*.sav\0\0";o.lpstrDefExt=L"sav";o.Flags=OFN_OVERWRITEPROMPT|OFN_PATHMUSTEXIST;if(!GetSaveFileNameW(&o))return;std::wofstream f(p);if(!f){MessageBoxW(hwnd,L"Impossible d'enregistrer.",L"Murim",MB_ICONERROR);return;}f<<state.started<<L'\n'<<state.ageMonths<<L'\n'<<state.money<<L'\n'<<state.seed<<L'\n'<<state.health<<L'\n'<<state.stamina<<L'\n'<<state.martialSkill<<L'\n'<<state.name<<L'\n'<<state.place<<L'\n'<<state.body<<L'\n'<<state.spirit<<L'\n'<<state.qi<<L'\n'<<state.trait<<L'\n';logLine(L"Partie sauvegardée.");}
void loadGame(HWND hwnd){OPENFILENAMEW o{};wchar_t p[MAX_PATH]=L"";o.lStructSize=sizeof(o);o.hwndOwner=hwnd;o.lpstrFile=p;o.nMaxFile=MAX_PATH;o.lpstrFilter=L"Murim Save (*.sav)\0*.sav\0\0";o.Flags=OFN_FILEMUSTEXIST|OFN_PATHMUSTEXIST;if(!GetOpenFileNameW(&o))return;std::wifstream f(p);if(!f){MessageBoxW(hwnd,L"Impossible de charger.",L"Murim",MB_ICONERROR);return;}GameState s;int st=0;f>>st>>s.ageMonths>>s.money>>s.seed>>s.health>>s.stamina>>s.martialSkill;f.ignore(1);std::getline(f,s.name);std::getline(f,s.place);std::getline(f,s.body);std::getline(f,s.spirit);std::getline(f,s.qi);std::getline(f,s.trait);if(!f){MessageBoxW(hwnd,L"Sauvegarde invalide.",L"Murim",MB_ICONERROR);return;}s.started=st!=0;s.world=murim::WorldEngine(s.seed);state=std::move(s);logLine(L"Partie chargée.");redraw(hwnd);}
void fullscreen(HWND hwnd){static bool full=false;static WINDOWPLACEMENT wp{sizeof(wp)};static LONG style=0;if(!full){style=GetWindowLongW(hwnd,GWL_STYLE);if(GetWindowPlacement(hwnd,&wp)&&(style&WS_OVERLAPPEDWINDOW)){MONITORINFO mi{sizeof(mi)};if(GetMonitorInfoW(MonitorFromWindow(hwnd,MONITOR_DEFAULTTONEAREST),&mi)){SetWindowLongW(hwnd,GWL_STYLE,style&~WS_OVERLAPPEDWINDOW);SetWindowPos(hwnd,HWND_TOP,mi.rcMonitor.left,mi.rcMonitor.top,mi.rcMonitor.right-mi.rcMonitor.left,mi.rcMonitor.bottom-mi.rcMonitor.top,SWP_NOOWNERZORDER|SWP_FRAMECHANGED);full=true;}}}else{SetWindowLongW(hwnd,GWL_STYLE,style);SetWindowPlacement(hwnd,&wp);SetWindowPos(hwnd,nullptr,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOZORDER|SWP_FRAMECHANGED);full=false;}}
LRESULT CALLBACK WndProc(HWND hwnd,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{hFont=CreateFontW(16,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,FF_DONTCARE,L"Segoe UI");hSmall=CreateFontW(13,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,FF_DONTCARE,L"Segoe UI");hAction=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_MULTILINE|ES_AUTOVSCROLL,430,350,500,62,hwnd,(HMENU)ID_ACTION_EDIT,GetModuleHandleW(nullptr),nullptr);hLog=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"Chronique du Jianghu\r\n",WS_CHILD|WS_VISIBLE|WS_VSCROLL|ES_MULTILINE|ES_READONLY,430,510,500,100,hwnd,nullptr,GetModuleHandleW(nullptr),nullptr);SendMessageW(hAction,WM_SETFONT,(WPARAM)hFont,TRUE);SendMessageW(hLog,WM_SETFONT,(WPARAM)hSmall,TRUE);addButton(hwnd,L"Nouvelle vie",ID_NEW);addButton(hwnd,L"Sauvegarder",ID_SAVE);addButton(hwnd,L"Charger",ID_LOAD);addButton(hwnd,L"Plein écran",ID_FULL);addButton(hwnd,L"Faire l'action",ID_ACTION);addButton(hwnd,L"S'entraîner",ID_TRAIN);addButton(hwnd,L"Se reposer",ID_REST);layout(hwnd);break;}case WM_PAINT:{PAINTSTRUCT p;BeginPaint(hwnd,&p);EndPaint(hwnd,&p);paintUI(hwnd);break;}case WM_SIZE:layout(hwnd);redraw(hwnd);break;case WM_DRAWITEM:{auto*d=(DRAWITEMSTRUCT*)l;if(!d||d->CtlType!=ODT_BUTTON)break;HBRUSH bg=CreateSolidBrush((d->itemState&ODS_SELECTED)?RGB(94,65,31):RGB(28,39,52));FillRect(d->hDC,&d->rcItem,bg);DeleteObject(bg);HBRUSH fr=CreateSolidBrush(RGB(80,91,103));FrameRect(d->hDC,&d->rcItem,fr);DeleteObject(fr);SetBkMode(d->hDC,TRANSPARENT);SetTextColor(d->hDC,RGB(232,224,210));wchar_t t[128];GetWindowTextW(d->hwndItem,t,128);DrawTextW(d->hDC,t,-1,&d->rcItem,DT_CENTER|DT_VCENTER|DT_SINGLELINE);break;}case WM_COMMAND:{int id=LOWORD(w);if(id==ID_NEW)newLife(hwnd);else if(id==ID_ADVANCE)advanceTime(hwnd);else if(id==ID_SAVE)saveGame(hwnd);else if(id==ID_LOAD)loadGame(hwnd);else if(id==ID_FULL)fullscreen(hwnd);else if(id==ID_ACTION)doAction(hwnd);else if(id==ID_TRAIN)train(hwnd);else if(id==ID_REST)rest(hwnd);break;}case WM_KEYDOWN:if(w==VK_F11)fullscreen(hwnd);break;case WM_DESTROY:if(portrait)delete portrait;GdiplusShutdown(gdiplusToken);PostQuitMessage(0);break;}return DefWindowProcW(hwnd,m,w,l);}
}

int APIENTRY wWinMain(HINSTANCE h,HINSTANCE,LPWSTR,int n){GdiplusStartupInput gi;GdiplusStartup(&gdiplusToken,&gi,nullptr);const wchar_t cls[]=L"MurimNativeRPG";WNDCLASSW wc{};wc.hInstance=h;wc.lpszClassName=cls;wc.lpfnWndProc=WndProc;wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);HWND hwnd=CreateWindowExW(0,cls,L"Murim — Les Mille Destins",WS_OVERLAPPEDWINDOW|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,1280,760,nullptr,nullptr,h,nullptr);if(!hwnd)return 1;ShowWindow(hwnd,n);UpdateWindow(hwnd);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wParam;}
